## Linear Regression

In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

x_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

m, n = np.shape(x_train)

print(x_train, '\n', y_train, '\n', f"m = {m}, n = {n}")

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]] 
 [460 232 178] 
 m = 3, n = 4


In [30]:
def zscore_normalize_feature_scaling(x):
    x_mean = np.mean(x, axis=0)
    x_std = np.std(x, axis=0)

    x_norm = ( x - x_mean ) / x_std
    return x_norm

# x_norm = zscore_normalize_feature_scaling(x_train)

# Plotting
# fig, ax = plt.subplots(1, 4, figsize=(12, 3))
# for i in range(len(ax)):
#     ax[i].scatter(x_norm[0:3,i], y_train)
# ax[0].set_ylabel('Price in 1000s')
# plt.show()

In [31]:
def prediction_function(x, w, b):
    f_wb = (x @ w) + b
    return f_wb

In [32]:
def cost_function(w, b):
    x_norm = zscore_normalize_feature_scaling(x_train)

    f_wb = prediction_function(x_norm, w, b)
    err = f_wb - y_train
    J_wb = (1 / (2*m)) * np.sum( np.square(err) )

    return J_wb

In [33]:
def compute_gradients(x, y, w, b):

    f_wb = prediction_function(x, w, b)
    err = f_wb - y

    dj_dw = (1/m) * (err @ x)
    dj_db = (1/m) * np.sum(err)

    return dj_dw, dj_db

In [34]:
def gradient_descent(x_train, y_train):
    w = np.zeros(n)
    b = 0
    x_norm = zscore_normalize_feature_scaling(x_train)

    iterations = 100000
    alpha = 0.01
    _lambda = 0.85

    for i in range(iterations):
        dj_dw, dj_db = compute_gradients(x_norm, y_train, w, b)
        w = w - alpha * dj_dw
        b = b - alpha * dj_db

    return w, b


In [35]:
def main():
    w, b = gradient_descent(x_train, y_train)
    print(w, '\n', b)

main()

[ 38.05161505  41.54327451 -30.98894656  36.34177447] 
 289.9999999999972
